version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn install
  post_build:
    commands:
      - echo "Post Build"
      - nohup java -jar project_2-0.0.1-SNAPSHOT.jar
artifacts:
  files:
   - '**/*'
   - 'appspec.yml'
  discard-paths: yes
