version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - echo "Post Build"
      - mvn package
artifacts:
  files:
   - target/project_2-0.0.1-SNAPSHOT.jar
