version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn package
    post_build:
      commands:
      - mv target/ROOT.war ROOT.war
artifacts:
  files:
    - ROOT.war
   - '**/*'
