version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn clean install
  post_build:
    commands:
      - echo "Post Build"
      - ls 
      - pwd
      - nohup java -jar ./target/project_2-0.0.1-SNAPSHOT.jar & echo $! > pidfile
artifacts:
  files:
   - '**/*'
  discard-paths: yes
